#Variables

my_string_variable = "My variable of text "
print(my_string_variable)

my_int_variable = 954253361233
print(my_int_variable)
print(type(my_int_variable))


my_bool_number = True
print(my_bool_number)

"""Cambio de variables
of integer to text
"""

my_int_to_str_variable = str(my_int_variable)
print(my_int_to_str_variable)
print(type(my_int_to_str_variable))

# of text to integer

my_str_to_int_variable = int(my_int_to_str_variable)
print(my_str_to_int_variable)
print(type(my_str_to_int_variable))

# Concatenacion  de variable en un Print

print (my_bool_number,my_str_to_int_variable,my_int_variable)

